### ISSUE TITLE
Some legend items do not translate

### ISSUE THREAD

**Issue by olejandro** [Tokni/klimaaftalen#57]
The following legend items appear as "legend.*" on the charts:
- Transport (elsk. lastbiler)
- Transportmidler (eksl. goods transport)

The corresponding entries are present in the translation files. Affected charts are located on tab5.

**Comment by olavurellefsen** [comment]
The problem was that the legend identifier contains a period (elsk. and eksl.). Please change this in the data sets going forward (done in the commit that fixed this)
